import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:sti_app/domain/entities/presensi/santri_presensi.dart';
import 'package:sti_app/domain/entities/result.dart';
import 'package:sti_app/domain/usecase/presensi/create_presensi_pertemuan/create_presensi_pertemuan.dart';
import '../../../../domain/entities/presensi/presensi_status.dart';
import '../../../../domain/entities/presensi/presensi_summary.dart';
import '../../../../domain/entities/presensi/presensi_pertemuan.dart';
import '../../repositories/user_repository/user_repository_provider.dart';
import '../../usecases/presensi/create_presensi_pertemuan_provider.dart';

part 'input_presensi_provider.g.dart';

@riverpod
class InputPresensiController extends _$InputPresensiController {
  @override
  FutureOr<void> build() {
    return null;
  }

  Future<void> submitPresensi({
    required String programId,
    required int pertemuanKe,
    required DateTime tanggal,
    required String materi,
    required List<SantriPresensi> daftarHadir,
    String? catatan,
  }) async {
    state = const AsyncLoading();

    try {
      // Generate summary
      final summary = _generateSummary(daftarHadir);

      // Create presensi pertemuan with summary
      final presensiPertemuan = PresensiPertemuan(
        id: '', // Will be generated by Firebase
        programId: programId,
        pertemuanKe: pertemuanKe,
        tanggal: tanggal,
        daftarHadir: daftarHadir,
        summary: summary,
        materi: materi,
        catatan: catatan,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      // Get usecase instance
      final createPresensi = ref.read(createPresensiPertemuanProvider);

      // Gunakan presensiPertemuan untuk createPresensi
      final result = await createPresensi(
        CreatePresensiPertemuanParams(
          programId: presensiPertemuan.programId,
          pertemuanKe: presensiPertemuan.pertemuanKe,
          tanggal: presensiPertemuan.tanggal,
          materi: presensiPertemuan.materi,
          catatan: presensiPertemuan.catatan,
          daftarHadir: presensiPertemuan.daftarHadir,
          summary: presensiPertemuan.summary,
        ),
      );

      state = switch (result) {
        Success(value: _) => const AsyncData(null),
        Failed(message: final msg) =>
          AsyncError(Exception(msg), StackTrace.current),
      };
    } catch (e, stack) {
      state = AsyncError(e, stack);
    }
  }

  PresensiSummary _generateSummary(List<SantriPresensi> daftarHadir) {
    int hadir = 0, sakit = 0, izin = 0, alpha = 0;

    for (var santri in daftarHadir) {
      switch (santri.status) {
        case PresensiStatus.hadir:
          hadir++;
        case PresensiStatus.sakit:
          sakit++;
        case PresensiStatus.izin:
          izin++;
        case PresensiStatus.alpha:
          alpha++;
      }
    }

    return PresensiSummary(
      totalSantri: daftarHadir.length,
      hadir: hadir,
      sakit: sakit,
      izin: izin,
      alpha: alpha,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );
  }

  Future<void> bulkUpdatePresensi({
    required String programId,
    required List<String> santriIds,
    required PresensiStatus status,
    String? keterangan,
    required int pertemuanKe, // Tambah ini
  }) async {
    state = const AsyncLoading();
    try {
      // Get santri details first
      final userRepository = ref.read(userRepositoryProvider);
      final daftarHadir = await Future.wait(
        santriIds.map((id) async {
          final user = await userRepository.getUser(uid: id);
          return SantriPresensi(
            santriId: id,
            santriName: user.resultValue?.name ?? '', // Fix missing santriName
            status: status,
            keterangan: keterangan,
          );
        }),
      );

      await submitPresensi(
        programId: programId,
        pertemuanKe: pertemuanKe,
        tanggal: DateTime.now(),
        materi: 'Bulk Update',
        daftarHadir: daftarHadir,
        catatan: 'Bulk update presensi',
      );
    } catch (e, stack) {
      state = AsyncError(e, stack);
    }
  }
}

@riverpod
bool isValidPresensiInput(
  IsValidPresensiInputRef ref, {
  required String programId,
  required int pertemuanKe,
  required String materi,
  required List<SantriPresensi> daftarHadir,
}) {
  if (programId.isEmpty || materi.isEmpty || daftarHadir.isEmpty) {
    return false;
  }

  if (pertemuanKe < 1 || pertemuanKe > 8) {
    return false;
  }

  return true;
}
